version: "3.4"
services:

  worker1:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env1
    ports:
      - 8001:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis1:
    image: redis:5

  postgres1:
    image: postgres:9.6
    environment:
      - POSTGRES_DB: sprf
      - POSTGRES_USER: sprf
      - POSTGRES_PASSWORD: secure_password
    volumes:
      - ./pgdata1:/var/lib/postgresql/db
    ports:
      - 5432:5432

  worker2:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env2
    ports:
      - 8000:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis2:
    image: redis:5

  postgres2:
    image: postgres:9.6
    environment:
      - POSTGRES_DB: sprf
      - POSTGRES_USER: sprf
      - POSTGRES_PASSWORD: secure_password
    volumes:
      - ./pgdata2:/var/lib/postgresql/db
    ports:
      - 5432:5432

  worker3:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env3
    ports:
      - 8000:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis3:
    image: redis:5

  postgres3:
    image: postgres:9.6
    environment:
      - POSTGRES_DB: sprf
      - POSTGRES_USER: sprf
      - POSTGRES_PASSWORD: secure_password
    volumes:
      - ./pgdata3:/var/lib/postgresql/db
    ports:
      - 5432:5432