version: "3.4"
services:

  worker1:
    #build:
    #  dockerfile: Dockerfile
    #  context: .
    #  network: host
    image: smart-program/sprf-worker:1
    env_file:
      - .env1
    ports:
      - 5001:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ipfs-files/:/tmp/ipfs-files/
    restart: always

  redis1:
    image: redis:5

  postgres1:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=sprf
      - POSTGRES_USER=sprf
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - ./pgdata1:/var/lib/postgresql/db

  worker2:
    image: smart-program/sprf-worker:1
    env_file:
      - .env2
    ports:
      - 5002:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ipfs-files/:/tmp/ipfs-files/
    restart: always

  redis2:
    image: redis:5

  postgres2:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=sprf
      - POSTGRES_USER=sprf
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - ./pgdata2:/var/lib/postgresql/db

  worker3:
    image: smart-program/sprf-worker:1
    env_file:
      - .env3
    ports:
      - 5003:5002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ipfs-files/:/tmp/ipfs-files/
    restart: always

  redis3:
    image: redis:5

  postgres3:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=sprf
      - POSTGRES_USER=sprf
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - ./pgdata3:/var/lib/postgresql/db
