version: "3.4"
services:

  worker1:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env
    ports:
      - 8001:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis1:
    image: redis:5

  worker2:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env
    ports:
      - 8000:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis2:
    image: redis:5

  worker3:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env
    ports:
      - 8000:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis3:
    image: redis:5