version: "3.4"
services:

  worker1:
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    env_file:
      - .env1
    ports:
      - 8000:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env

  transaction-validator:
    image: smart-program/transaction-validator
    env_file:
      - .env1
    ports:
      - 3000:3000

  redis:
    image: redis:5
    ports:
      - 6379:6379
